UniversityMgtApp/Models/CourseEnrollment.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace UniversityMgtApp.Models
{
    public class CourseEnrollment
    {
        public int EnrollmentId { get; set; }

        [Required(ErrorMessage = "Registration number is required")]
        [Display(Name = "Student Reg. No.")]
        public string StudentRegistrationNumber { get; set; }

        public int StudentId { get; set; }

        [Display(Name = "Name")]
        public string StudentName { get; set; }
        public string Email { get; set; }

        [Display(Name = "Department")]
        public string DepartmentName { get; set; }

        [Required(ErrorMessage = "Course is required")]
        [Display(Name = "Select Course")]
        public int CourseId { get; set; }
        public Course Course { get; set; }

        [Display(Name = "Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime EnrollDate { get; set; }
    }
}

UniversityMgtApp/Controllers/CourseEnrollmentController.cs
using System;
using System.Web.Mvc;
using UniversityMgtApp.BLL;
using UniversityMgtApp.Models;

namespace UniversityMgtApp.Controllers
{
    public class CourseEnrollmentController : Controller
    {
        public ActionResult Save()
        {
            StudentManager studentManager = new StudentManager();
            ViewBag.StudentList = studentManager.GetAllStudents();
            return View();
        }

        [HttpPost]
        public ActionResult Save(CourseEnrollment courseEnrollment)
        {
            StudentManager studentManager = new StudentManager();
            ViewBag.StudentList = studentManager.GetAllStudents();

            if (ModelState.IsValid)
            {
                try
                {
                    CourseAssignManager courseAssignManager = new CourseAssignManager();
                    if (courseAssignManager.SaveCourseEnroll(courseEnrollment))
                    {
                        ViewBag.Success = "Course enroll successfully";
                        ModelState.Clear();
                    }
                }
                catch (Exception exception)
                {
                    ViewBag.Exist = exception.Message;
                }
            }
            return View();
        }

        public JsonResult GetStudentDetail(int? studentId)
        {
            StudentManager studentManager = new StudentManager();
            var studentDetail = studentManager.GetStudentDetail(studentId);

            CourseManager courseManager = new CourseManager();
            var courseDetail = courseManager.GetCourseDetail(studentId);

            var studentAndCourseDetail = new {studentDetail = studentDetail, courseDetail = courseDetail};

            return Json(studentAndCourseDetail, JsonRequestBehavior.AllowGet);
        }
	}
}

UniversityMgtApp/Views/CourseEnrollment/Save.cshtml
@model UniversityMgtApp.Models.CourseEnrollment

@{
    ViewBag.Title = "Save";
}

<style>
    fieldset.scheduler-border {
        border: solid 1px #DDD !important;
        padding: 0 55px;
        border-bottom: none;
        border-radius: 10px;
        width: 600px;
    }

    legend.scheduler-border {
        width: auto !important;
        border: none;
        font-size: 20px;
        font-weight: bold;
    }
</style>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true)

        <fieldset class="scheduler-border">
            <legend class="scheduler-border">Enroll In a Course</legend>

            <div class="form-group">
                @Html.LabelFor(model => model.StudentRegistrationNumber, new {@class = "col-md-4"})
                <div class="col-md-6">
                    @Html.DropDownListFor(model => model.StudentRegistrationNumber, new SelectList(ViewBag.StudentList, "StudentId", "RegNumber"), "--Select Student--", new {@class = "form-control"})
                    @Html.HiddenFor(model=>model.StudentId)
                    @Html.ValidationMessageFor(model => model.StudentRegistrationNumber)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StudentName, new { @class = "col-md-4" })
                <div class="col-md-6">
                    @Html.TextBoxFor(model => model.StudentName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.StudentName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, new { @class = "col-md-4" })
                <div class="col-md-6">
                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Email)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DepartmentName, new { @class = "col-md-4" })
                <div class="col-md-6">
                    @Html.TextBoxFor(model => model.DepartmentName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.DepartmentName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CourseId, new { @class = "col-md-4" })
                <div class="col-md-6">
                    @Html.DropDownListFor(model => model.CourseId, new SelectList(""), "--Select Course--", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CourseId)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.EnrollDate, new { @class = "col-md-4" })
                <div class="col-md-6">
                    @Html.TextBoxFor(model => model.EnrollDate, new { @class = "form-control datePicker" })
                    @Html.ValidationMessageFor(model => model.EnrollDate)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-4 col-md-6">
                    <input type="submit" value="Enroll" class="btn btn-default"/>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-4 col-md-6">
                    <span style="color:green; font-weight:bold;">@ViewBag.Success</span>
                    <span style="color:red; font-weight:bold;">@ViewBag.Exist</span>
                </div>
            </div>
        </fieldset>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $(function () {
                $(".datePicker").datepicker({ dateFormat: 'mm/dd/yy', type: Text });
            });

            $("#StudentRegistrationNumber").change(function () {
                var studentId = $("#StudentRegistrationNumber").val();

                $('#StudentName').val("");
                $('#Email').val("");
                $('#DepartmentName').val("");
                $('#StudentId').val("");
                $('#CourseId').empty();

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetStudentDetail", "CourseEnrollment")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify({ studentId: studentId }),

                    success: function (studentAndCourseDetail) {
                        $("#StudentId").val(studentAndCourseDetail.studentDetail.StudentId);
                        $("#StudentName").val(studentAndCourseDetail.studentDetail.StudentName);
                        $("#Email").val(studentAndCourseDetail.studentDetail.Email);
                        $("#DepartmentName").val(studentAndCourseDetail.studentDetail.DepartmentName);

                        $("#CourseId").append('<option value="">' + "--Select Course--" + '</option>');
                        $.each(studentAndCourseDetail.courseDetail, function (key, value) {
                            $("#CourseId").append('<option value=' + value.CourseId + '>' + value.CourseName + '</option>');
                        });
                    },

                });
            });



        });
    </script>
}