UniversityMgtApp/Controllers/ClassScheduleController.cs
using System.Web.Mvc;
using UniversityMgtApp.BLL;

namespace UniversityMgtApp.Controllers
{
    public class ClassScheduleController : Controller
    {
        public ActionResult Index()
        {
            DepartmentManager departmentManager = new DepartmentManager();
            ViewBag.Department = departmentManager.GetAllDepartments();

            return View();
        }

        [HttpPost]
        public JsonResult ViewClassSchedule(int? departmentId)
        {
            AllocationClassRoomManager allocationClassRoomManager = new AllocationClassRoomManager();
            var classScheduleStatus = allocationClassRoomManager.GetClassScheduleStatus(departmentId);
            
            return Json(classScheduleStatus, JsonRequestBehavior.AllowGet);
        }
	}
}

UniversityMgtApp/Views/ClassSchedule/Index.cshtml
@{
    ViewBag.Title = "ViewCourse";
}

<style>
    fieldset.scheduler-border {
        border: solid 1px #DDD !important;
        padding: 0px 35px;
        border-bottom: none;
        border-radius: 10px;
        width: 600px;
    }

    legend.scheduler-border {
        width: auto !important;
        border: none;
        font-size: 20px;
        font-weight: bold;
    }

    table th {
        text-align: center;
        border: 1px solid #e9e9e9;
        height: 40px;
    }

    table tr td {
        border: 1px solid #e9e9e9;
        padding: 3px;
        height: 30px;
    }

    #DepartmentId {
        width: 200px;
    }
</style>


<fieldset class="scheduler-border">
    <legend class="scheduler-border">View Class Schedule and Room Allocation</legend>

    <table width="100%">
        <tr>
            <td style="text-align: right; border: none;">Department</td>
            <td style="border: none">
                @Html.DropDownList("DepartmentId", new SelectList(ViewBag.Department, "DepartmentId", "DepartmentName"), "--Select Department--", new { @class = "form-control" })
            </td>
        </tr>
    </table>

    <br />
    <table style="width: 100%" id="ViewCourseStatic">
        <tr style="background-color: #e9e9e9;">
            <th>Course Code</th>
            <th>Name</th>
            <th style="width:255px;">Schedule Info</th>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td></td>
            <td></td>
        </tr>
    </table>

    <br />
</fieldset>


<script src="~/Scripts/jquery-1.10.2.min.js"></script>

@section scripts
{
    <script>
        $(document).ready(function() {
            $("#DepartmentId").change(function() {
                var departmentId = $("#DepartmentId").val();

                $("#ViewCourseStatic").empty();

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("ViewClassSchedule", "ClassSchedule")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify({ departmentId: departmentId }),

                    success: function(courses) {
                        $("#ViewCourseStatic").append('<tr style="background-color: #e9e9e9; height:40px;"><th>Course Code</th><th>Name</th><th style="width:255px;">Schedule Info</th></tr>');
                        $.each(courses, function(key, value) {
                            $("#ViewCourseStatic").append('<tr><td>' + value.CourseCode + '</td><td>' + value.CourseName + '</td><td>' + value.ScheduleInfo + '</td></tr>');
                        });
                    },

                });
            });
        });
    </script>
}