UniversityMgtApp/Models/CourseAssign.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace UniversityMgtApp.Models
{
    public class CourseAssign
    {
        public int CourseAssignId { get; set; }

        [Required(ErrorMessage = "Department is required")]
        [Display(Name = "Department")]
        public int DepartmentId { get; set; }
        public virtual ICollection<Department> Department { get; set; }

        [Required(ErrorMessage = "Teacher name is required")]
        [Display(Name = "Teacher")]
        public int TeacherId { get; set; }
        public virtual ICollection<Teacher> Teacher { get; set; }

        [Display(Name = "Credit To Be Taken")]
        public double CreditToBeTaken { get; set; }

        [Display(Name = "Remaining Credit")]
        public double RemainingCredit { get; set; }

        [Required(ErrorMessage = "Course code is required")]
        [Display(Name = "Course Code")]
        public int CourseId { get; set; }
        public virtual ICollection<Course> Course { get; set; }

        [Display(Name = "Name")]
        public string CourseName { get; set; }

        [Display(Name = "Credit")]
        public decimal CourseCredit { get; set; }
    }
}

UniversityMgtApp/Controllers/CourseAssignController.cs
using System;
using System.Web.Mvc;
using UniversityMgtApp.BLL;
using UniversityMgtApp.Models;

namespace UniversityMgtApp.Controllers
{
    public class CourseAssignController : Controller
    {
        public ActionResult Save()
        {
            DepartmentManager departmentManager = new DepartmentManager();
            ViewBag.Department = departmentManager.GetAllDepartments();

            return View();
        }

        [HttpPost]
        public ActionResult Save(CourseAssign courseAssign)
        {
            DepartmentManager departmentManager = new DepartmentManager();
            ViewBag.Department = departmentManager.GetAllDepartments();

            if (ModelState.IsValid)
            {
                try
                {
                    CourseAssignManager courseAssignManager = new CourseAssignManager();

                    if (courseAssignManager.SaveAssignCourse(courseAssign))
                    {
                        ViewBag.Success = "Assign Successfully";
                        ModelState.Clear();
                    }
                }
                catch (Exception exception)
                {
                    ViewBag.Exist = exception.Message;
                }
            }
            return View();
        }

        [HttpPost]
        public JsonResult GetTeacher(int? departmentId)
        {
            TeacherManager teacherManager = new TeacherManager();
            CourseAssignManager courseAssignManager = new CourseAssignManager();

            var teachers = teacherManager.GetAllTeachers(departmentId);
            var courses = courseAssignManager.GetAllCourseDetails(departmentId);

            var teacherCourses = new { courses = courses, teachers = teachers };
            return Json(teacherCourses, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GetTeacherDetail(int? teacherId)
        {
            TeacherManager teacherManager = new TeacherManager();
            var teacherDetails = teacherManager.GetTeacherDetails(teacherId);
            var teacherAssignCredit = teacherManager.GetTeacherAssignCredit(teacherId);

            var remainingCredit = teacherDetails.CreditToBeTaken - teacherAssignCredit;

            var creditToBeTakenRemainingCredit =
                new {remainingCredit = remainingCredit, teacherDetails = teacherDetails};

            return Json(creditToBeTakenRemainingCredit, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GetCourseDetail(int? courseId)
        {
            CourseAssignManager courseAssignManager = new CourseAssignManager();
            var courseDetails = courseAssignManager.GetCourseDetails(courseId);

            return Json(courseDetails, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ViewCourse()
        {
            DepartmentManager departmentManager = new DepartmentManager();
            ViewBag.Department = departmentManager.GetAllDepartments();

            return View();
        }

        public JsonResult CourseStatic(int? departmentId)
        {
            CourseAssignManager courseAssignManager = new CourseAssignManager();

            var courses = courseAssignManager.GetAllCourseDetails(departmentId);

            return Json(courses, JsonRequestBehavior.AllowGet);
        }
	}
}

UniversityMgtApp/Views/CourseAssign/Save.cshtml
@model UniversityMgtApp.Models.CourseAssign

@{
    ViewBag.Title = "Save";
}

<style>
    fieldset.scheduler-border {
        border: solid 1px #DDD !important;
        padding: 0 55px;
        border-bottom: none;
        border-radius: 10px;
        width: 600px;
    }

    legend.scheduler-border {
        width: auto !important;
        border: none;
        font-size: 20px;
        font-weight: bold;
    }
</style>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true)
        <fieldset class="scheduler-border">
            <legend class="scheduler-border">Course Assign to Teacher</legend>

            <div class="form-group">
                @Html.LabelFor(model => model.DepartmentId, new {@class = "col-md-5"})
                <div class="col-md-6">
                    @Html.DropDownListFor(model => model.DepartmentId, new SelectList(ViewBag.Department, "DepartmentId", "DepartmentName"), "--Select Department--", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.DepartmentId, "", new { @class = "validation" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TeacherId, new {@class = "col-md-5"})
                <div class="col-md-6">
                    @Html.DropDownListFor(model => model.TeacherId, new SelectList(""), "--Select Teacher--", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TeacherId, "", new { @class = "validation" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CreditToBeTaken, new {@class = "col-md-5"})
                <div class="col-md-6">
                    @Html.TextBoxFor(model => model.CreditToBeTaken, new { @class = "form-control", @readonly = "ReadOnly" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.RemainingCredit, new {@class = "col-md-5"})
                <div class="col-md-6">
                    @Html.TextBoxFor(model => model.RemainingCredit, new { @class = "form-control", @readonly = "ReadOnly" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CourseId, new {@class = "col-md-5"})
                <div class="col-md-6">
                    @Html.DropDownListFor(model => model.CourseId, new SelectList(""), "--Select Course--", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "validation" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CourseName, new {@class = "col-md-5"})
                <div class="col-md-6">
                    @Html.TextBoxFor(model => model.CourseName, new { @class = "form-control", @readonly = "ReadOnly" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CourseCredit, new {@class = "col-md-5"})
                <div class="col-md-6">
                    @Html.TextBoxFor(model => model.CourseCredit, new { @class = "form-control", @readonly = "ReadOnly" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-5 col-md-6">
                    <input id="saveButton" type="submit" value="Assign" class="btn btn-default" />
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-5 col-md-6">
                    <span style="color:green; font-weight:bold;">@ViewBag.Success</span>
                    <span style="color:red; font-weight:bold;">@ViewBag.Exist</span>
                </div>
            </div>
        </fieldset>
</div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

<script>
    $(document).ready(function() {
        $("#DepartmentId").change(function() {
            var departmentId = $("#DepartmentId").val();

            $('#TeacherId').empty();
            $('#CourseId').empty();
            $('#CreditToBeTaken').val("");
            $('#RemainingCredit').val("");
            $('#CourseName').val("");
            $('#CourseCredit').val("");

            $.ajax({
                type: "POST",
                url: '@Url.Action("GetTeacher", "CourseAssign")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify({ departmentId: departmentId }),

                success: function(teacherCourses) {
                    $("#TeacherId").append('<option value="">' + "--Select Teacher--" + '</option>');
                    $.each(teacherCourses.teachers, function(key, value) {
                        $("#TeacherId").append('<option value=' + value.TeacherId + '>' + value.TeacherName + '</option>');
                    });

                    $("#CourseId").append('<option value="">' + "--Select Course--" + '</option>');
                    $.each(teacherCourses.courses, function(key, value) {
                        $("#CourseId").append('<option value=' + value.CourseId + '>' + value.CourseCode + '</option>');
                    });
                },

            });
        });

        $("#TeacherId").change(function() {
            var teacherId = $("#TeacherId").val();

            $('#CreditToBeTaken').val("");
            $('#RemainingCredit').val("");

            $.ajax({
                type: "POST",
                url: '@Url.Action("GetTeacherDetail", "CourseAssign")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify({ teacherId: teacherId }),

                success: function (creditToBeTakenRemainingCredit) {
                    $("#CreditToBeTaken").val(creditToBeTakenRemainingCredit.teacherDetails.CreditToBeTaken);
                    $("#RemainingCredit").val(creditToBeTakenRemainingCredit.remainingCredit);
                },

            });
        });

        $("#CourseId").change(function() {
            var courseId = $("#CourseId").val();

            $('#CourseName').val("");
            $('#CourseCredit').val("");

            $.ajax({
                type: "POST",
                url: '@Url.Action("GetCourseDetail", "CourseAssign")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify({ courseId: courseId }),

                success: function(courseDetails) {
                    $("#CourseName").val(courseDetails.CourseName);
                    $("#CourseCredit").val(courseDetails.CourseCredit);
                },

            });
        });

        $("#saveButton").on("click", function() {

            var a = parseFloat($('#RemainingCredit').val());
            var b = parseFloat($('#CourseCredit').val());
            var c = a + b;
            var d = parseFloat($('#CreditToBeTaken').val());

            if (a != d) {
                if (a < b) {

                    if (confirm("Course credit is more than teacher's remaining credit. Are you sure you want to Save this?")) {
                    } else {
                        return false;
                    }
                }
            }
        });
    });
</script>
}

UniversityMgtApp/Views/CourseAssign/ViewCourse.cshtml
@{
    ViewBag.Title = "ViewCourse";
}

<style>
    fieldset.scheduler-border {
        border: solid 1px #DDD !important;
        padding: 0px 35px;
        border-bottom: none;
        border-radius: 10px;
        width: 600px;
    }

    legend.scheduler-border {
        width: auto !important;
        border: none;
        font-size: 20px;
        font-weight: bold;
    }

    table th {
        text-align: center;
        border: 1px solid #e9e9e9;
        height: 40px;
    }

    table tr td {
        border: 1px solid #e9e9e9;
        padding: 3px;
        height: 30px;
    }

    #DepartmentId {
        width: 200px;
    }

</style>


<fieldset class="scheduler-border">
    <legend class="scheduler-border">View Course Statics</legend>

    <table  width="100%">
        <tr>
            <td style="text-align: right; border: none;">Department</td>
            <td style="border: none">
                @Html.DropDownList("DepartmentId", new SelectList(ViewBag.Department, "DepartmentId", "DepartmentName"), "--Select Department--", new { @class = "form-control" })
            </td>
        </tr>
    </table>

    <br />
    <table style="width: 100%" id="ViewCourseStatic">
        <tr style="background-color: #e9e9e9;">
            <th>Code</th>
            <th>Name/Title</th>
            <th>Semester</th>
            <th>Assigned To</th>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </table>

    <br />
</fieldset>

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")

        <script>
        $(document).ready(function() {
            $("#DepartmentId").change(function() {
                var departmentId = $("#DepartmentId").val();

                $("#ViewCourseStatic").empty();

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("CourseStatic", "CourseAssign")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify({ departmentId: departmentId }),

                    success: function(courses) {
                        $("#ViewCourseStatic").append('<tr style="background-color: #e9e9e9; height:40px;"><th>Code</th><th>Name/Title</th><th>Semester</th><th>Assigned To</th></tr>');
                        $.each(courses, function(key, value) {
                            $("#ViewCourseStatic").append('<tr><td>' + value.CourseCode + '</td><td>' + value.CourseName + '</td><td>' + value.Semester + ' Semester' + '</td><td>' + value.TeacherName + '</td></tr>');
                        });
                    },

                });
            });
        });
    </script>

}